### Stappen te doorlopen

1. Begin met een gewone dataframe van de csv
2. Replace de d_ in de datum kolommen
3. Maak een temp dataframe met alleen de datum kolommen
4. Verander de namen van de datum kolommen naar date
5. Voeg de 'pnt_id' kolom van de oorspronkelijke csv toe aan de temp
6. Maak van de temp een dataframe waarbij de datum kolommen values worden 
7. Verander de kolom namen van de temp dataframe
8. Selecteer het id van de betreffende satelliet (Work In Progress, is nu nog hard coded, wordt later uit de bestandsnaam gehaald)
9. Maak een nieuwe kolom 'sat_id' met het betreffende id en voeg die toe aan de dataframe

In [2]:
import numpy as np
import pandas as pd
from sqlalchemy import create_engine
engine = create_engine('postgresql://postgres:Welkom01!@10.30.1.10:5432/POC')
file = "D:\Documents\Data Science\PROJECT\data_grondwaterontrekking\prov_overijssel_eindhoven_rsat2_asc_xf_v2_ds_hoge_punten.csv"

In [3]:
def convert_dataframe_datums(file) :
    # 1. Begin met een gewone dataframe van de csv 
    original_df = pd.read_csv(file)
    # 2. Replace de d_ in de datum kolommen
    original_df.columns = original_df.columns.str.replace('d_', '')
    # 3. Maak een temp dataframe met alleen de datum kolommen
    temp = original_df.iloc[:,9:-2]
    # 4. Verander de namen van de datum kolommen naar date
    temp.columns = pd.to_datetime(temp.columns).date
    # 5. Voeg de 'pnt_id' kolom van de oorspronkelijke csv toe aan de temp
    temp['pnt_id'] = original_df['pnt_id']
    # 6. Maak van de temp een dataframe waarbij de datum kolommen values worden
    temp = temp.set_index('pnt_id').stack().reset_index()
    # 7. Verander de kolom namen van de temp dataframe
    result = temp.rename(columns={'level_1':'datum', 0:'meting'})
    # 8. Selecteer het id van de betreffende satelliet (Work In Progress, is nu nog hard coded, wordt later uit de bestandsnaam gehaald) 
    sat_id = pd.read_sql_query( """select sat_id from satelliet where sat_naam = 'rsatxf' and type = 'HDA'""", engine).iloc[0, 0]
    # 9. Maak een nieuwe kolom 'sat_id' met het betreffende id en voeg die toe aan de dataframe
    result['sat_id'] = sat_id
    return result

In [4]:
converted_rsatxf_hda = convert_dataframe_datums(file)

In [5]:
converted_rsatxf_hda

                 pnt_id       datum  meting  sat_id
0        L373252P179009  2015-04-07  0.0000       5
1        L373252P179009  2015-05-01 -0.0048       5
2        L373252P179009  2015-06-18 -0.0079       5
3        L373252P179009  2015-07-12 -0.0035       5
4        L373252P179009  2015-08-05 -0.0040       5
5        L373252P179009  2015-08-29 -0.0053       5
6        L373252P179009  2015-09-22 -0.0096       5
7        L373252P179009  2015-10-16 -0.0075       5
8        L373252P179009  2015-11-09 -0.0044       5
9        L373252P179009  2015-12-03  0.0039       5
10       L373252P179009  2015-12-27 -0.0136       5
11       L373252P179009  2016-01-20 -0.0072       5
12       L373252P179009  2016-02-13 -0.0042       5
13       L373252P179009  2016-03-08 -0.0033       5
14       L373252P179009  2016-04-01 -0.0075       5
15       L373252P179009  2016-04-25 -0.0020       5
16       L373252P179009  2016-05-19 -0.0076       5
17       L373252P179009  2016-06-12 -0.0045       5
18       L373252P179009  2016-07-06 -0.0003       5
19       L373252P179009  2016-07-30 -0.0045       5
20       L373252P179009  2016-08-23 -0.0046       5
21       L373252P179009  2016-09-16 -0.0031       5
22       L373252P179009  2016-10-10 -0.0065       5
23       L373252P179009  2016-11-03 -0.0038       5
24       L373252P179009  2016-11-27 -0.0078       5
25       L373252P179009  2016-12-21 -0.0064       5
26       L373252P179009  2017-01-14 -0.0051       5
27       L373252P179009  2017-02-07 -0.0074       5
28       L373252P179009  2017-03-03 -0.0057       5
29       L373252P179009  2017-03-27 -0.0062       5
...                 ...         ...     ...     ...
2048954  L496739P138204  2017-01-14  0.0013       5
2048955  L496739P138204  2017-02-07 -0.0017       5
2048956  L496739P138204  2017-03-03 -0.0039       5
2048957  L496739P138204  2017-03-27 -0.0027       5
2048958  L496739P138204  2017-04-20 -0.0003       5
2048959  L496739P138204  2017-05-14 -0.0009       5
2048960  L496739P138204  2017-06-07 -0.0014       5
2048961  L496739P138204  2017-07-01 -0.0032       5
2048962  L496739P138204  2017-07-25  0.0006       5
2048963  L496739P138204  2017-08-18  0.0005       5
2048964  L496739P138204  2017-09-11 -0.0021       5
2048965  L496739P138204  2017-10-05 -0.0011       5
2048966  L496739P138204  2017-10-29  0.0005       5
2048967  L496739P138204  2017-11-22 -0.0022       5
2048968  L496739P138204  2017-12-16 -0.0068       5
2048969  L496739P138204  2018-01-09  0.0015       5
2048970  L496739P138204  2018-02-02 -0.0013       5
2048971  L496739P138204  2018-02-26  0.0008       5
2048972  L496739P138204  2018-03-22  0.0006       5
2048973  L496739P138204  2018-04-15 -0.0048       5
2048974  L496739P138204  2018-05-09  0.0006       5
2048975  L496739P138204  2018-06-02 -0.0045       5
2048976  L496739P138204  2018-06-26 -0.0038       5
2048977  L496739P138204  2018-07-20 -0.0057       5
2048978  L496739P138204  2018-08-13 -0.0040       5
2048979  L496739P138204  2018-09-06 -0.0068       5
2048980  L496739P138204  2018-09-30 -0.0068       5
2048981  L496739P138204  2018-10-24 -0.0040       5
2048982  L496739P138204  2018-11-17 -0.0043       5
2048983  L496739P138204  2018-12-11 -0.0058       5

[2048984 rows x 4 columns]

# Testen om hem in de database tabel meting te krijgen

In [8]:
testdfvoortabel = converted_rsatxf_hda[:100]

In [23]:
testdfvoortabel.to_sql('meting', con=engine, if_exists='append', index=False)

In [30]:
testdfvoorderde = converted_rsatxf_hda[10:20]

In [32]:
testdfvoorderde.to_sql('meting', con=engine, if_exists='append', index=False)

In [33]:
pd.read_sql_query("""WITH CTE (pnt_id, datum, meting,sat_id, DuplicateCount)
AS
(
  SELECT pnt_id, datum, meting,sat_id,
  ROW_NUMBER() OVER(PARTITION BY pnt_id, datum, meting, sat_id ORDER BY pnt_id) AS DuplicateCount
  FROM meting
) SELECT * from CTE""", engine)

             pnt_id       datum  meting sat_id  duplicatecount
0    L373223P179007  2015-04-07  0.0000      5               1
1    L373223P179007  2015-05-01  0.0012      5               1
2    L373223P179007  2015-06-18 -0.0016      5               1
3    L373223P179007  2015-07-12  0.0015      5               1
4    L373223P179007  2015-08-05  0.0061      5               1
5    L373223P179007  2015-08-29  0.0047      5               1
6    L373223P179007  2015-09-22 -0.0020      5               1
7    L373223P179007  2015-10-16 -0.0016      5               1
8    L373223P179007  2015-11-09  0.0063      5               1
9    L373223P179007  2015-12-03  0.0063      5               1
10   L373223P179007  2015-12-27 -0.0001      5               1
11   L373223P179007  2016-01-20  0.0001      5               1
12   L373223P179007  2016-02-13 -0.0007      5               1
13   L373223P179007  2016-03-08  0.0034      5               1
14   L373223P179007  2016-04-01 -0.0077      5               1
15   L373223P179007  2016-04-25  0.0017      5               1
16   L373223P179007  2016-05-19  0.0035      5               1
17   L373223P179007  2016-06-12 -0.0003      5               1
18   L373223P179007  2016-07-06  0.0045      5               1
19   L373223P179007  2016-07-30  0.0002      5               1
20   L373223P179007  2016-08-23 -0.0046      5               1
21   L373223P179007  2016-09-16  0.0043      5               1
22   L373223P179007  2016-10-10 -0.0004      5               1
23   L373223P179007  2016-11-03 -0.0015      5               1
24   L373223P179007  2016-11-27 -0.0010      5               1
25   L373223P179007  2016-12-21 -0.0026      5               1
26   L373223P179007  2017-01-14  0.0021      5               1
27   L373223P179007  2017-02-07 -0.0019      5               1
28   L373223P179007  2017-03-03  0.0032      5               1
29   L373223P179007  2017-03-27 -0.0021      5               1
..              ...         ...     ...    ...             ...
100  L373252P179009  2017-01-14 -0.0051      5               1
101  L373252P179009  2017-02-07 -0.0074      5               1
102  L373252P179009  2017-03-03 -0.0057      5               1
103  L373252P179009  2017-03-27 -0.0062      5               1
104  L373252P179009  2017-04-20 -0.0080      5               1
105  L373252P179009  2017-05-14 -0.0081      5               1
106  L373252P179009  2017-06-07  0.0011      5               1
107  L373252P179009  2017-07-01  0.0005      5               1
108  L373252P179009  2017-07-25 -0.0041      5               1
109  L373252P179009  2017-08-18 -0.0054      5               1
110  L373252P179009  2017-09-11 -0.0072      5               1
111  L373252P179009  2017-10-05 -0.0077      5               1
112  L373252P179009  2017-10-29  0.0007      5               1
113  L373252P179009  2017-11-22 -0.0083      5               1
114  L373252P179009  2017-12-16 -0.0081      5               1
115  L373252P179009  2018-01-09 -0.0086      5               1
116  L373252P179009  2018-02-02 -0.0084      5               1
117  L373252P179009  2018-02-26 -0.0054      5               1
118  L373252P179009  2018-03-22 -0.0076      5               1
119  L373252P179009  2018-04-15 -0.0114      5               1
120  L373252P179009  2018-05-09 -0.0076      5               1
121  L373252P179009  2018-06-02 -0.0092      5               1
122  L373252P179009  2018-06-26 -0.0039      5               1
123  L373252P179009  2018-07-20 -0.0078      5               1
124  L373252P179009  2018-08-13 -0.0053      5               1
125  L373252P179009  2018-09-06 -0.0059      5               1
126  L373252P179009  2018-09-30 -0.0084      5               1
127  L373252P179009  2018-10-24 -0.0044      5               1
128  L373252P179009  2018-11-17 -0.0070      5               1
129  L373252P179009  2018-12-11 -0.0097      5               1

[130 rows x 5 columns]