### Stappen te doorlopen

1. Begin met een gewone dataframe van de csv
2. Replace de d_ in de datum kolommen
3. Maak een temp dataframe met alleen de datum kolommen
4. Verander de namen van de datum kolommen naar date
5. Voeg de 'pnt_id' kolom van de oorspronkelijke csv toe aan de temp
6. Maak van de temp een dataframe waarbij de datum kolommen values worden 
7. Verander de kolom namen van de temp dataframe
8. Selecteer het id van de betreffende satelliet (Work In Progress, is nu nog hard coded, wordt later uit de bestandsnaam gehaald)
9. Maak een nieuwe kolom 'sat_id' met het betreffende id en voeg die toe aan de dataframe

In [35]:
import numpy as np
import pandas as pd
from sqlalchemy import create_engine
engine = create_engine('postgresql://postgres:Welkom01!@10.30.1.10:5432/POC')
file = "D:\Documents\Data Science\PROJECT\data_zoutcavernes\prov_overijssel_eindhoven_rsat2_asc_xf_v2_ds_hoge_punten.csv"

In [36]:
def convert_dataframe_datums(file) :
    # 1. Begin met een gewone dataframe van de csv 
    original_df = pd.read_csv(file)
    # 2. Replace de d_ in de datum kolommen
    original_df.columns = original_df.columns.str.replace('d_', '')
    # 3. Maak een temp dataframe met alleen de datum kolommen
    temp = original_df.iloc[:,9:-2]
    # 4. Verander de namen van de datum kolommen naar date
    temp.columns = pd.to_datetime(temp.columns).date
    # 5. Voeg de 'pnt_id' kolom van de oorspronkelijke csv toe aan de temp
    temp['pnt_id'] = original_df['pnt_id']
    # 6. Maak van de temp een dataframe waarbij de datum kolommen values worden
    temp = temp.set_index('pnt_id').stack().reset_index()
    # 7. Verander de kolom namen van de temp dataframe
    result = temp.rename(columns={'level_1':'datum', 0:'meting'})
    # 8. Selecteer het id van de betreffende satelliet (Work In Progress, is nu nog hard coded, wordt later uit de bestandsnaam gehaald) 
    sat_id = pd.read_sql_query( """select sat_id from satelliet where sat_naam = 'rsatxf' and type = 'HDA'""", engine).iloc[0, 0]
    # 9. Maak een nieuwe kolom 'sat_id' met het betreffende id en voeg die toe aan de dataframe
    result['sat_id'] = sat_id
    return result

In [37]:
converted_rsatxf_hda = convert_dataframe_datums(file)

In [38]:
converted_rsatxf_hda

                 pnt_id       datum  meting  sat_id
0        L321677P230658  2015-04-07  0.0000       5
1        L321677P230658  2015-05-01 -0.0024       5
2        L321677P230658  2015-06-18  0.0010       5
3        L321677P230658  2015-07-12 -0.0004       5
4        L321677P230658  2015-08-05 -0.0033       5
5        L321677P230658  2015-08-29 -0.0006       5
6        L321677P230658  2015-09-22 -0.0049       5
7        L321677P230658  2015-10-16 -0.0030       5
8        L321677P230658  2015-11-09  0.0091       5
9        L321677P230658  2015-12-03  0.0018       5
10       L321677P230658  2015-12-27 -0.0004       5
11       L321677P230658  2016-01-20  0.0043       5
12       L321677P230658  2016-02-13  0.0028       5
13       L321677P230658  2016-03-08  0.0052       5
14       L321677P230658  2016-04-01  0.0019       5
15       L321677P230658  2016-04-25  0.0035       5
16       L321677P230658  2016-05-19  0.0022       5
17       L321677P230658  2016-06-12  0.0047       5
18       L321677P230658  2016-07-06 -0.0025       5
19       L321677P230658  2016-07-30  0.0039       5
20       L321677P230658  2016-08-23  0.0011       5
21       L321677P230658  2016-09-16 -0.0029       5
22       L321677P230658  2016-10-10  0.0043       5
23       L321677P230658  2016-11-03  0.0023       5
24       L321677P230658  2016-11-27  0.0064       5
25       L321677P230658  2016-12-21  0.0027       5
26       L321677P230658  2017-01-14  0.0066       5
27       L321677P230658  2017-02-07 -0.0074       5
28       L321677P230658  2017-03-03  0.0019       5
29       L321677P230658  2017-03-27  0.0041       5
...                 ...         ...     ...     ...
1013122  L339356P226277  2017-01-14 -0.0072       5
1013123  L339356P226277  2017-02-07 -0.0050       5
1013124  L339356P226277  2017-03-03 -0.0051       5
1013125  L339356P226277  2017-03-27  0.0030       5
1013126  L339356P226277  2017-04-20  0.0034       5
1013127  L339356P226277  2017-05-14  0.0039       5
1013128  L339356P226277  2017-06-07  0.0046       5
1013129  L339356P226277  2017-07-01  0.0021       5
1013130  L339356P226277  2017-07-25 -0.0060       5
1013131  L339356P226277  2017-08-18  0.0028       5
1013132  L339356P226277  2017-09-11 -0.0006       5
1013133  L339356P226277  2017-10-05 -0.0012       5
1013134  L339356P226277  2017-10-29  0.0025       5
1013135  L339356P226277  2017-11-22 -0.0011       5
1013136  L339356P226277  2017-12-16 -0.0021       5
1013137  L339356P226277  2018-01-09 -0.0022       5
1013138  L339356P226277  2018-02-02 -0.0030       5
1013139  L339356P226277  2018-02-26  0.0045       5
1013140  L339356P226277  2018-03-22 -0.0042       5
1013141  L339356P226277  2018-04-15  0.0048       5
1013142  L339356P226277  2018-05-09 -0.0017       5
1013143  L339356P226277  2018-06-02  0.0055       5
1013144  L339356P226277  2018-06-26  0.0004       5
1013145  L339356P226277  2018-07-20  0.0000       5
1013146  L339356P226277  2018-08-13  0.0030       5
1013147  L339356P226277  2018-09-06 -0.0001       5
1013148  L339356P226277  2018-09-30  0.0013       5
1013149  L339356P226277  2018-10-24 -0.0040       5
1013150  L339356P226277  2018-11-17 -0.0024       5
1013151  L339356P226277  2018-12-11  0.0010       5

[1013152 rows x 4 columns]

# Testen om hem in de database tabel meting te krijgen

In [34]:
converted_rsatxf_hda.to_sql('meting', con=engine, if_exists='append', index=False)

KeyboardInterrupt: