In [40]:
import pandas as pd
from sqlalchemy import create_engine
import datetime
import numpy as np
import re

In [45]:
engine = create_engine('postgresql://postgres:Welkom01!@10.30.1.10:5432/POC')
query = "SELECT * FROM meting WHERE pnt_id = 'L485027P138209' LIMIT 50"
df = pd.read_sql(query, engine)

In [46]:
print(df)
print(df.info())

         id          pnt_id       datum  meting sat_id
0   9623986  L485027P138209  2015-04-07  0.0000      6
1   9623987  L485027P138209  2015-05-01 -0.0020      6
2   9623988  L485027P138209  2015-06-18 -0.0012      6
3   9623989  L485027P138209  2015-07-12 -0.0010      6
4   9623990  L485027P138209  2015-08-05  0.0023      6
5   9623991  L485027P138209  2015-08-29 -0.0031      6
6   9623992  L485027P138209  2015-09-22 -0.0135      6
7   9623993  L485027P138209  2015-10-16 -0.0019      6
8   9623994  L485027P138209  2015-11-09 -0.0117      6
9   9623995  L485027P138209  2015-12-03 -0.0072      6
10  9623996  L485027P138209  2015-12-27 -0.0050      6
11  9623997  L485027P138209  2016-01-20 -0.0112      6
12  9623998  L485027P138209  2016-02-13 -0.0023      6
13  9623999  L485027P138209  2016-03-08 -0.0041      6
14  9624000  L485027P138209  2016-04-01  0.0007      6
15  9624001  L485027P138209  2016-04-25 -0.0101      6
16  9624002  L485027P138209  2016-05-19 -0.0037      6
17  9624003  L485027P138209  2016-06-12 -0.0067      6
18  9624004  L485027P138209  2016-07-06 -0.0068      6
19  9624005  L485027P138209  2016-07-30 -0.0103      6
20  9624006  L485027P138209  2016-08-23 -0.0073      6
21  9624007  L485027P138209  2016-09-16 -0.0025      6
22  9624008  L485027P138209  2016-10-10 -0.0106      6
23  9624009  L485027P138209  2016-11-03 -0.0171      6
24  9624010  L485027P138209  2016-11-27 -0.0120      6
25  9624011  L485027P138209  2016-12-21 -0.0106      6
26  9624012  L485027P138209  2017-01-14 -0.0099      6
27  9624013  L485027P138209  2017-02-07 -0.0144      6
28  9624014  L485027P138209  2017-03-03 -0.0073      6
29  9624015  L485027P138209  2017-03-27 -0.0083      6
30  9624016  L485027P138209  2017-04-20 -0.0081      6
31  9624017  L485027P138209  2017-05-14 -0.0118      6
32  9624018  L485027P138209  2017-06-07 -0.0118      6
33  9624019  L485027P138209  2017-07-01 -0.0129      6
34  9624020  L485027P138209  2017-07-25 -0.0095      6
35  9624021  L485027P138209  2017-08-18 -0.0187      6
36  9624022  L485027P138209  2017-09-11 -0.0180      6
37  9624023  L485027P138209  2017-10-05 -0.0199      6
38  9624024  L485027P138209  2017-10-29 -0.0195      6
39  9624025  L485027P138209  2017-11-22 -0.0210      6
40  9624026  L485027P138209  2017-12-16 -0.0287      6
41  9624027  L485027P138209  2018-01-09 -0.0255      6
42  9624028  L485027P138209  2018-02-02 -0.0239      6
43  9624029  L485027P138209  2018-02-26 -0.0201      6
44  9624030  L485027P138209  2018-03-22 -0.0212      6
45  9624031  L485027P138209  2018-04-15 -0.0185      6
46  9624032  L485027P138209  2018-05-09 -0.0181      6
47  9624033  L485027P138209  2018-06-02 -0.0234      6
48  9624034  L485027P138209  2018-06-26 -0.0199      6
49  9624035  L485027P138209  2018-07-20 -0.0218      6
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
id        50 non-null int64
pnt_id    50 non-null object
datum     50 non-null object
meting    50 non-null float64
sat_id    50 non-null object
dtypes: float64(1), int64(1), object(3)
memory usage: 2.0+ KB
None

In [60]:
df['datum'] = pd.to_datetime(df['datum'])

In [69]:
start_20151 = pd.Timestamp(year=2015, month=1, day=1)
end_20151 = pd.Timestamp(year=2015, month=6, day=30)
vijftien1 = (df['datum'] > start_20151) & (df['datum'] <= end_20151)
vijftien1 = df.loc[vijftien1]

start_20152 = pd.Timestamp(year=2015, month=7, day=1)
end_20152 = pd.Timestamp(year=2015, month=12, day=30)
vijftien2 = (df['datum'] > start_20152) & (df['datum'] <= end_20152)
vijftien2 = df.loc[vijftien2]

start_20161 = pd.Timestamp(year=2016, month=1, day=1)
end_20161 = pd.Timestamp(year=2016, month=6, day=30)
zestien1 = (df['datum'] > start_20161) & (df['datum'] <= end_20161)
zestien1 = df.loc[zestien1]

start_20162 = pd.Timestamp(year=2016, month=7, day=1)
end_20162 = pd.Timestamp(year=2016, month=12, day=30)
zestien2 = (df['datum'] > start_20162) & (df['datum'] <= end_20162)
zestien2 = df.loc[zestien2]

start_20171 = pd.Timestamp(year=2017, month=1, day=1)
end_20171 = pd.Timestamp(year=2017, month=6, day=30)
zeventien1 = (df['datum'] > start_20171) & (df['datum'] <= end_20171)
zeventien1 = df.loc[zeventien1]

start_20172 = pd.Timestamp(year=2017, month=7, day=1)
end_20172 = pd.Timestamp(year=2017, month=12, day=30)
zeventien2 = (df['datum'] > start_20172) & (df['datum'] <= end_20172)
zeventien2 = df.loc[zeventien2]

start_20181 = pd.Timestamp(year=2018, month=1, day=1)
end_20181 = pd.Timestamp(year=2018, month=6, day=30)
achtien1 = (df['datum'] > start_20181) & (df['datum'] <= end_20181)
achtien1 = df.loc[achtien1]

start_20182 = pd.Timestamp(year=2017, month=7, day=1)
end_20182 = pd.Timestamp(year=2017, month=12, day=30)
achtien2 = (df['datum'] > start_20182) & (df['datum'] <= end_20182)
achtien2 = df.loc[achtien2]

print(vijftien1)
print(vijftien2)
print(zestien1)
print(zestien2)
print(zeventien1)
print(zeventien2)
print(achtien1)
print(achtien2)

        id          pnt_id      datum  meting sat_id
0  9623986  L485027P138209 2015-04-07  0.0000      6
1  9623987  L485027P138209 2015-05-01 -0.0020      6
2  9623988  L485027P138209 2015-06-18 -0.0012      6
         id          pnt_id      datum  meting sat_id
3   9623989  L485027P138209 2015-07-12 -0.0010      6
4   9623990  L485027P138209 2015-08-05  0.0023      6
5   9623991  L485027P138209 2015-08-29 -0.0031      6
6   9623992  L485027P138209 2015-09-22 -0.0135      6
7   9623993  L485027P138209 2015-10-16 -0.0019      6
8   9623994  L485027P138209 2015-11-09 -0.0117      6
9   9623995  L485027P138209 2015-12-03 -0.0072      6
10  9623996  L485027P138209 2015-12-27 -0.0050      6
         id          pnt_id      datum  meting sat_id
11  9623997  L485027P138209 2016-01-20 -0.0112      6
12  9623998  L485027P138209 2016-02-13 -0.0023      6
13  9623999  L485027P138209 2016-03-08 -0.0041      6
14  9624000  L485027P138209 2016-04-01  0.0007      6
15  9624001  L485027P138209 2016-04-25 -0.0101      6
16  9624002  L485027P138209 2016-05-19 -0.0037      6
17  9624003  L485027P138209 2016-06-12 -0.0067      6
         id          pnt_id      datum  meting sat_id
18  9624004  L485027P138209 2016-07-06 -0.0068      6
19  9624005  L485027P138209 2016-07-30 -0.0103      6
20  9624006  L485027P138209 2016-08-23 -0.0073      6
21  9624007  L485027P138209 2016-09-16 -0.0025      6
22  9624008  L485027P138209 2016-10-10 -0.0106      6
23  9624009  L485027P138209 2016-11-03 -0.0171      6
24  9624010  L485027P138209 2016-11-27 -0.0120      6
25  9624011  L485027P138209 2016-12-21 -0.0106      6
         id          pnt_id      datum  meting sat_id
26  9624012  L485027P138209 2017-01-14 -0.0099      6
27  9624013  L485027P138209 2017-02-07 -0.0144      6
28  9624014  L485027P138209 2017-03-03 -0.0073      6
29  9624015  L485027P138209 2017-03-27 -0.0083      6
30  9624016  L485027P138209 2017-04-20 -0.0081      6
31  9624017  L485027P138209 2017-05-14 -0.0118      6
32  9624018  L485027P138209 2017-06-07 -0.0118      6
         id          pnt_id      datum  meting sat_id
34  9624020  L485027P138209 2017-07-25 -0.0095      6
35  9624021  L485027P138209 2017-08-18 -0.0187      6
36  9624022  L485027P138209 2017-09-11 -0.0180      6
37  9624023  L485027P138209 2017-10-05 -0.0199      6
38  9624024  L485027P138209 2017-10-29 -0.0195      6
39  9624025  L485027P138209 2017-11-22 -0.0210      6
40  9624026  L485027P138209 2017-12-16 -0.0287      6
         id          pnt_id      datum  meting sat_id
41  9624027  L485027P138209 2018-01-09 -0.0255      6
42  9624028  L485027P138209 2018-02-02 -0.0239      6
43  9624029  L485027P138209 2018-02-26 -0.0201      6
44  9624030  L485027P138209 2018-03-22 -0.0212      6
45  9624031  L485027P138209 2018-04-15 -0.0185      6
46  9624032  L485027P138209 2018-05-09 -0.0181      6
47  9624033  L485027P138209 2018-06-02 -0.0234      6
48  9624034  L485027P138209 2018-06-26 -0.0199      6
         id          pnt_id      datum  meting sat_id
34  9624020  L485027P138209 2017-07-25 -0.0095      6
35  9624021  L485027P138209 2017-08-18 -0.0187      6
36  9624022  L485027P138209 2017-09-11 -0.0180      6
37  9624023  L485027P138209 2017-10-05 -0.0199      6
38  9624024  L485027P138209 2017-10-29 -0.0195      6
39  9624025  L485027P138209 2017-11-22 -0.0210      6
40  9624026  L485027P138209 2017-12-16 -0.0287      6

In [71]:
def gemiddelde(df):
    aantal = len(df['meting'])
    meting = df['meting']
    totaal = meting.sum()
    gemiddelde = (totaal / aantal)
    return gemiddelde

gemiddelde(vijftien1)

-0.0010666666666666665

In [64]:
vijftien = df.loc[vijftien1]
print(vijftien)

        id          pnt_id      datum  meting sat_id
0  9623986  L485027P138209 2015-04-07  0.0000      6
1  9623987  L485027P138209 2015-05-01 -0.0020      6
2  9623988  L485027P138209 2015-06-18 -0.0012      6

In [61]:
print(df['datum'])

0    2015-04-07
1    2015-05-01
2    2015-06-18
3    2015-07-12
4    2015-08-05
5    2015-08-29
6    2015-09-22
7    2015-10-16
8    2015-11-09
9    2015-12-03
10   2015-12-27
11   2016-01-20
12   2016-02-13
13   2016-03-08
14   2016-04-01
15   2016-04-25
16   2016-05-19
17   2016-06-12
18   2016-07-06
19   2016-07-30
20   2016-08-23
21   2016-09-16
22   2016-10-10
23   2016-11-03
24   2016-11-27
25   2016-12-21
26   2017-01-14
27   2017-02-07
28   2017-03-03
29   2017-03-27
30   2017-04-20
31   2017-05-14
32   2017-06-07
33   2017-07-01
34   2017-07-25
35   2017-08-18
36   2017-09-11
37   2017-10-05
38   2017-10-29
39   2017-11-22
40   2017-12-16
41   2018-01-09
42   2018-02-02
43   2018-02-26
44   2018-03-22
45   2018-04-15
46   2018-05-09
47   2018-06-02
48   2018-06-26
49   2018-07-20
Name: datum, dtype: datetime64[ns]